global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['metrics-server:9100']

  - job_name: 'flask-api'
    static_configs:
      - targets: ['flask-api:5000']

  - job_name: 'jupyter-notebook'
    static_configs:
      - targets: ['host.docker.internal:8001']
